name = "heyprompt-platform"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
entry-point = "."

[vars]
# Environment variables
NEXTAUTH_URL = "http://localhost:3000"
NEXTAUTH_SECRET = "your-nextauth-secret"

[[d1_databases]]
binding = "DB"
database_name = "heyprompt-platform"
database_id = "d4b930e4-0fe0-4264-83de-3eeb7ac706a3"

[[d1_databases]]
binding = "PROD_DB"
database_name = "heyprompt-platform"
database_id = "d4b930e4-0fe0-4264-83de-3eeb7ac706a3"

[env.preview]
vars = { ENV = "preview" }

[env.production]
vars = { ENV = "production" } 