name = "heyprompt-platform"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
entry-point = "."

# Add special configuration for NextAuth API routes
[[routes]]
pattern = "/api/auth/.*"
node_compat = true
nodejs_compat = true

[vars]
# Environment variables
NEXTAUTH_URL = "http://localhost:3000"
NEXTAUTH_SECRET = "your-nextauth-secret"

[[d1_databases]]
binding = "DB"
database_name = "heyprompt-auth"
database_id = "your-database-id"

[[d1_databases]]
binding = "PROD_DB"
database_name = "heyprompt-auth-prod"
database_id = "your-prod-database-id"

[env.preview]
vars = { ENV = "preview" }

[env.production]
vars = { ENV = "production" } 